name: Deploy website
on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: deploy-website
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Deploy to page branches
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pages
          build_dir: dist